title: KoorunG blog
description: KoorunG's Github Pages
theme: just-the-docs

url: https://koorung.github.io/

aux_links:
  Template Repository: https://github.com/koorung/koorung.github.io

plugins:
  - jekyll-default-layout
