title: KoorunG's blog
description: KoorunG's Github Pages
theme: just-the-docs

url: https://koorung.github.io/

aux_links:
  KoorunG's Github: https://github.com/KoorunG

plugins:
  - jekyll-default-layout
