name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.170.0
        with:
          ruby-version: 'latest'
          bundler-cache: true
          working-directory: '${{ github.workspace }}/docs'
          cache-version: 0
          
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.9
