# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
    paths: ["docs/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.170.0
        with:
          ruby-version: '3.2.0'
          bundler-cache: true
          working-directory: '${{ github.workspace }}/docs'
          cache-version: 0

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v4.0.0

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "docs/_site"
        env:
          JEKYLL_ENV: production

      # - name: Build Jekyll for GitHub Pages
      #   uses: actions/jekyll-build-pages@v1.0.9
      #   with:
      #     source: "docs/"
      #     destination: "docs/_site"
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: "docs/_site/"
          

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.3
          
